### ISSUE TITLE
Replace Upcoming listing w/ a weekly highs and lows temperature graph and an aligned table for other data

### ISSUE THREAD

**Issue by cadadr** [cadadr/forecast.el#14]
I've changed the interface for _Upcoming_ forecast to a more dense and glanceable tabular and graphical format.  Find attached a screenshot belo.  I wonder if I should

- keep the old UI and add the graph as an optional UI (enable via variable)
- keep the old UI, but make the new one default (revert via variable)
- get rid of the old UI and go with the new one

I haven't pushed the relevant changes upstream yet.

![scr](https://cloud.githubusercontent.com/assets/9742985/20860720/99f4174a-b987-11e6-97ec-46af85bc7607.png)

**Comment by mnsanghvi** [comment]
The tabular/graphical format is much better.  I would keep the old UI, but make the new UI the default.
