### ISSUE TITLE
Visibility should not be a percentage.

### ISSUE THREAD

**Issue by mnsanghvi** [cadadr/forecast.el#15]
The data provided by the API, as mentioned at https://darksky.net/dev/docs/response, states that 

> visibility optional
> The average visibility in miles, capped at 10 miles.

Based on that, it should be displayed as a distance, depending on the value of forecast-units.  It would either be miles or km.  "uk2" uses miles, instead of km, as per https://darksky.net/dev/docs/forecast.

**Comment by mnsanghvi** [comment]
I will see if I can generate a pull request with the needed changes.

**Comment by cadadr** [comment]
I'm going to push the patch for the new UI in a bit, which will fix this issue too.  Sorry if you already spent time on it.

**Comment by cadadr** [comment]
Pushed new patch and closed this issue, please report if does not solve the problem for you.

**Comment by mnsanghvi** [comment]
The new version is good.  Thanks for the quick turnaround.

**Comment by cadadr** [comment]
You're welcome.
-- 
İ. V. Göktuğ Kayaalp                           <http://www.gkayaalp.com>
                        PGP pubkey: <http://www.gkayaalp.com/pubkey.asc>
