### ISSUE TITLE
calendar-latitude, calendar-longitude variables

### ISSUE THREAD

**Issue by kaushalmodi** [cadadr/forecast.el#17]
Hello,

I was browsing through the forecast.el after a long time, and I see that forecast-latitude has changed to calendar-latitude, and the same for longitude, and location name.

These calendar-* variables are defcustoms from solar.el (part of Emacs), not calendar.el. Looks like you are requiring calendar instead of solar in your package.

If that's the case, can you please fix this? Thanks.

**Comment by cadadr** [comment]
Fixed, thanks a lot! (by commit ea2a116662a1cfe69ec2f95f4b4dca0c31f057e4)
