### ISSUE TITLE
Incorrect upcoming week info

### ISSUE THREAD

**Issue by kaushalmodi** [cadadr/forecast.el#18]
The upcoming week information graph created by forecast.el is very incorrect.

Here is what the package shows:

![image](https://cloud.githubusercontent.com/assets/3578197/21730990/374766de-d420-11e6-93e9-298532cdd620.png)

And here is what's actual (I know that the upcoming weekend is frigid!), and also shown by darksky.net:

![image](https://cloud.githubusercontent.com/assets/3578197/21731037/5fd3b17a-d420-11e6-91e2-531fa6b8988e.png)

I see no correlation between the days or the temperature numbers between forecast.el and darksky.net.

**Comment by kaushalmodi** [comment]
Ah! The bug is that the upcoming graph is printed in mirror fashion but the Day names printed (Fri Sat Sun ..) are correct.

**Comment by cadadr** [comment]
Hi, thanks a lot for all your patches, I've merged all of them just now.  I've made a silly error with the hourly graph and carried it over here too... I fixed the hourly a couple days ago.  Sorry for the inconvenience, and thanks again for the fixes.

**Comment by kaushalmodi** [comment]
You are welcome. Thanks for accepting the patches. This is a very cool package.

**Comment by cadadr** [comment]
You're very welcome, thanks for your kind words :smile: .
