### ISSUE TITLE
Mis-alignment on the Precipitation row in upcoming graph

### ISSUE THREAD

**Issue by kaushalmodi** [cadadr/forecast.el#24]
Hi,

The precipitation row looks like this to me:

![image](https://cloud.githubusercontent.com/assets/3578197/21745042/4309dad0-d4f0-11e6-89e9-a1f0c39340aa.png)

Before I submit a PR for this, I would like to understand if you too see the same or it's just me due to the fonts I use.

If I do the below:

```
diff --git a/forecast.el b/forecast.el
index 3f01e31..63b1627 100644
--- a/forecast.el
+++ b/forecast.el
@@ -679,7 +679,7 @@ wind directions."
     (mapc (lambda (p)
             (let ((pp (car p)) (pt (cdr p)))
               (insert (if (zerop pp)
-                          "        "
+                          "       "
                         (format " % 2d%% %s" (* 100 pp)
                                 (cond ((string= pt "rain") "⛆")
                                       ((string= pt "snow") "❄")))))))
```

the alignment almost gets fixed for me:

![image](https://cloud.githubusercontent.com/assets/3578197/21745059/8728908a-d4f0-11e6-89cc-fe9b60486b24.png)

Though it is still not perfect, probably because of the rain/snow unicode characters.

**Comment by TopSlick** [comment]
Thx for your nice work !
I see the report as in file attached. Indeed 'Precipitation'-label needs correction on alignment.
![image](https://cloud.githubusercontent.com/assets/10288679/21748905/551ff9ec-d591-11e6-8d2e-2d38e830ea78.png)

**Comment by kaushalmodi** [comment]
@TopSlick Thanks. So the alignment changes quite a bit of the precipitation is absent for one of the days. Might need a good solution to align the unicode characters which are slightly wider than regular characters. 

BTW as the day names abbreviation are 2 character wide instead of 3 characters, they are grossly misaligned. That needs to be fixed too.

**Comment by cadadr** [comment]
@TopSlick WRT the day name abbrevs, could you please try the following
patch, or tell me your locale so that I can test against this:

```
--- a/forecast.el
+++ b/forecast.el
@@ -691,7 +691,8 @@ wind directions."
                       (t " |   | "))))
       (newline))
     (forecast--insert-format
-     "Day:  %s\n" (mapconcat (lambda (tm) (format-time-string "  %a  " tm)) time ""))
+     "Day:  %s\n" (mapconcat (lambda (tm)
+                               (format-time-string "  %3a  " tm)) time ""))
     ;; precipitation
     (insert "      ")
     (mapc (lambda (p)
```

@kaushalmodi I don't really know if it's possible to have a constant
precipitation line in the table w/o giving up on unicode characters,
even though I really like them.  Maybe render them with a wee bit
smaller font size?

**Comment by cadadr** [comment]
20b000458215a110f41e980577799f224b8bf2b3 corrects the format string for the precipitation row of the table.  Now the only thing that causes the misalingment are the unicode characters.

**Comment by kaushalmodi** [comment]
Thanks. This looks good. I understand the limitation caused by using the unicode characters. But I also agree that that this is not worth giving up those snow/rain characters.

That latest commit, significantly improves the precipitation alignment.

**Comment by cadadr** [comment]
@kaushalmodi you're welcome,  I actually tried w/ R and S for rain and snow, looks ugly...  I really don't know what to do to improve.

@TopSlick I've just pushed a patch that fixes your issue wrt the alignment of day labels.

**Comment by kaushalmodi** [comment]
@cadadr 

>  I actually tried w/ R and S for rain and snow, looks ugly... I really don't know what to do to improve.

I agree, the unicode is better :)
