### ISSUE TITLE
Wrong coordinates in request-url

### ISSUE THREAD

**Issue by dnbarbato** [cadadr/forecast.el#26]
In the function definition of forecast--get-forecast in the string request-url the coordinates are truncated. This causes darksky to return the forecast for the wrong coordinates (e.g 40,-3 instead of 40.414,-3.685 which are about 74 km apart).
This can be fixed by using %f instead of %d in the format control string.

```diff
diff -u ~/.emacs.d/elpa/forecast-0.6.3/forecast.el ~/.emacs.d/elpa/forecast-0.6.3/forecast.el.old
--- ~/.emacs.d/elpa/forecast-0.6.3/forecast.el.old	2017-09-23 19:13:38.296314068 +0200
+++ ~/.emacs.d/elpa/forecast-0.6.3/forecast.el	2017-09-23 19:19:19.939077588 +0200
@@ -412,7 +412,7 @@
               (string-empty-p forecast-api-key))
       (user-error "Forecast: `forecast-api-key' not set"))
     (setf request-url
-          (format "%s/forecast/%s/%d,%d?%s"
+          (format "%s/forecast/%s/%f,%f?%s"
                   forecast-api-url
                   forecast-api-key
                   la lo

Diff finished.  Sat Sep 23 19:26:13 2017
```

**Comment by cadadr** [comment]
Hi @dnbarbato,

thanks a lot, I've installed and pushed your patch, and made a bugfix
release with it.  Sorry for the silly bug, weird that it went unnoticed
all this time...

-- 
İ. Göktuğ Kayaalp              http://www.gkayaalp.com/index.html
self@gkayaalp.com    🎀            PGP = 024C 30DD 597D 142B 49AC
Plaintext please!  {UTF8}  Fingerprint   40EB 465C D949 B101 2427
