### ISSUE TITLE
Not getting valid forecasts. 

### ISSUE THREAD

**Issue by anoduck** [cadadr/forecast.el#5]
I am not sure if this has anything to do with the emacs package or forecast.io, but every time I run forecast, I receive a forecast that does not even come close to reflecting upon my geographical area. I am walking around in shorts and a t shirt on a beautiful sunny day, and it says that it is below 15 degrees Fahrenheit with a chance of snow flurries later in the day. 
I have checked my GPS coordinates and they are correct...
...a lil help, please...

**Comment by anoduck** [comment]
I pulled a good one on that file, my ADHD must have been on overdrive. I discovered that I made the lovely newb mistake of forgetting to add a negative (-) to one of the GPS numbers. Once it was added, it worked perfectly. Sorry I even opened up this issue, the package works like a charm. Thanks.

**Comment by cadadr** [comment]
Hi, I'm happy that it works for you now, you're welcome.  Everybody makes such mistakes once in a while, no problem :smile:
