### ISSUE TITLE
moon symbols don't appear properly

### ISSUE THREAD

**Issue by emacsomancer** [cadadr/forecast.el#6]
I have the unicode-fonts package installed, but the moon symbols don't appear (rather in their place are the gibberish boxes)

**Comment by cadadr** [comment]
On Sat, Nov 14 2015 at  3:14:43 am EET, emacsomancer <notifications@github.com> wrote:
> I have the unicode-fonts package installed, but the moon symbols don't
> appear (rather in their place are the gibberish boxes)

These caracters are  implemented in a very little number  of fonts, none
well-known.  Please try  the Quivira(*) font, which  contains the needed
characters.  Set the face ‘forecast-moon-phase’ to use it:

    (set-face-attribute 'forecast-moon-phase nil
                        :font "Quivira")

(*) http://quivira-font.com/


>
> —
> Reply to this email directly or view it on GitHub.
>
>

-- 
İ. Göktuğ Kayaalp.
http://gkayaalp.com/

**Comment by emacsomancer** [comment]
That fixes it.
